# Find all the available rules by running:
# swiftlint rules
disabled_rules: # rule identifiers to exclude from running
  - class_delegate_protocol
  - cyclomatic_complexity
  - file_length
  - identifier_name
  - line_length
  - trailing_whitespace
  - type_body_length
  - type_name
  - weak_delegate
  # Non-production projects only
  - function_body_length
opt_in_rules: # some rules are only opt-in
included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
